---

- name: MariaDB is running
  hosts: database_prod
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
  tasks:
    - name: MariaDB is installed
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ mariadb_packages }}"
      when: ansible_distribution == "RedHat"
    - name: start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: true
