---

- name: stat module
  hosts: servera.lab.example.com
  gather_facts: no
  tasks:
    - name: lanza el modulo stat
      stat:  
        path: /etc/passwd
      register: result
    - name: output results
      debug:
        var: result.stat.checksum
