- name: Use the fetch module to retrieve secure logs files
  hosts: all
  remote_user: root
  tasks:
    - name: Fetch the /var/log/secure log file
      fetch:
        src: /var/log/secure
        dest: secure-backups
        flat: no

