- name: Using the file module to ensure SELinux file contexts
  hosts: all
  remote_user: root
  tasks:
    - name: selinux file contexts is set to defaults
      file:
        path: /home/devops/users.txt
        seuser: _default
        serole: _default
        setype: _default
        selevel: _default

