- name: schedule at task
  hosts: webservers
  become: true
  become_user: devops
  tasks:
    - name: at task
      at:
        command: "date > ~/my_at_time\n"
        count: 1
        units: minutes
        unique: yes
        state: present
