- name: configure vsftpd
  hosts: ftpservers
  vars_files: 
    - vars/vars.yml
    - vars/defaults-template.yml
  tasks:
    - name: install vsftpd
      yum:
        name: "{{ vsftpd_package }}"
        state: latest
    - name: start and enable service
      service:
        name: "{{ vsftpd_service }}"
        state: started
        enabled: yes
    - name: template config file
      template:
        src: vsftpd.conf.j2
        dest: "{{ vsftpd_config_file }}"
        owner: root
        group: root
        mode: 0600
      notify: restart vsftpd
    - name: firewalld installed
      yum:
        name: firewalld
        state: latest
    - name: open ftp port
      firewalld:
        service: ftp
        state: enabled
        permanent: yes
        immediate: yes
    - name: open passive ftp port
      firewalld:
        port: 21000-21020/tcp
        state: enabled
        permanent: yes
        immediate: yes
  handlers:
    - name: restart vsftpd
      service:
        name: "{{ vsftpd_service }}"
        state: restarted
